// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateJournalPostReq struct {
	Title   string   `json:"title,optional"`   // 标题，不传则自动生成
	Content string   `json:"content,optional"` // 正文
	Date    string   `json:"date,optional"`    // 日记日期，不传则默认今天
	Mood    string   `json:"mood,optional"`    // 心情，不传则默认 calm
	Tags    []string `json:"tags,optional"`    // 标签
	Pinned  bool     `json:"pinned,optional"`  // 是否置顶
}

type IdPathReq struct {
	Id string `path:"id"` // 日记 ID
}

type JournalPost struct {
	Id        string   `json:"id"`        // 日记 ID（UUID）
	Title     string   `json:"title"`     // 标题
	Content   string   `json:"content"`   // 正文（Markdown）
	Date      string   `json:"date"`      // 日记日期，格式 YYYY-MM-DD
	Mood      string   `json:"mood"`      // 心情：great / good / calm / low
	Tags      []string `json:"tags"`      // 标签列表
	Pinned    bool     `json:"pinned"`    // 是否置顶
	UpdatedAt string   `json:"updatedAt"` // 最后编辑时间，格式 YYYY-MM-DD HH:mm
}

type ListJournalPostsReq struct {
	Q          string `form:"q,optional"`                   // 关键词，匹配标题/正文/标签/心情
	Tag        string `form:"tag,optional"`                 // 按标签筛选
	Mood       string `form:"mood,optional"`                // 按心情筛选，传 all 或不传表示全部
	DateFilter string `form:"dateFilter,optional"`          // 时间范围：all / week（近 7 天）/ month（近 30 天）
	Page       int    `form:"page,optional,default=1"`      // 页码，从 1 开始
	PageSize   int    `form:"pageSize,optional,default=20"` // 每页条数
}

type ListJournalPostsResp struct {
	List     []JournalPost `json:"list"`     // 当前页数据
	Total    int64         `json:"total"`    // 符合条件的总条数
	Page     int           `json:"page"`     // 当前页码
	PageSize int           `json:"pageSize"` // 每页条数
}

type LoginReq struct {
	Username string `json:"username"` // 账号（邮箱或用户名）
	Password string `json:"password"` // 密码
}

type LoginResp struct {
	Token string `json:"token"` // JWT 访问令牌，后续请求放在 Authorization: Bearer <token>
}

type StatsResp struct {
	MonthCount   int64  `json:"monthCount"`   // 本月日记篇数
	AverageWords int64  `json:"averageWords"` // 全库平均字数（去空白后）
	TopTag       string `json:"topTag"`       // 使用最多的标签
	TotalCount   int64  `json:"totalCount"`   // 日记总篇数
}

type UpdateJournalPostReq struct {
	Title   string   `json:"title,optional"`   // 标题
	Content string   `json:"content,optional"` // 正文，可为空字符串
	Date    string   `json:"date,optional"`    // 日记日期
	Mood    string   `json:"mood,optional"`    // 心情
	Tags    []string `json:"tags,optional"`    // 标签
	Pinned  *bool    `json:"pinned,optional"`  // 是否置顶，指针类型用于区分未传与 false
}
