// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	journalpost "journal-service/internal/handler/journalpost"
	public "journal-service/internal/handler/public"
	"journal-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Cors},
			[]rest.Route{
				{
					// 日记列表
					Method:  http.MethodGet,
					Path:    "/journal-posts",
					Handler: journalpost.ListJournalPostsHandler(serverCtx),
				},
				{
					// 新建日记
					Method:  http.MethodPost,
					Path:    "/journal-posts",
					Handler: journalpost.CreateJournalPostHandler(serverCtx),
				},
				{
					// 日记详情
					Method:  http.MethodGet,
					Path:    "/journal-posts/:id",
					Handler: journalpost.GetJournalPostHandler(serverCtx),
				},
				{
					// 更新日记
					Method:  http.MethodPut,
					Path:    "/journal-posts/:id",
					Handler: journalpost.UpdateJournalPostHandler(serverCtx),
				},
				{
					// 删除日记
					Method:  http.MethodDelete,
					Path:    "/journal-posts/:id",
					Handler: journalpost.DeleteJournalPostHandler(serverCtx),
				},
				{
					// 日记统计
					Method:  http.MethodGet,
					Path:    "/stats",
					Handler: journalpost.GetStatsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: public.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
